spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

swagger:
  show: true

mybatis-plus:
#  mybatis-plus日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
