server:
  port: 8160

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: @package.environment@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        max-idle: 5
        min-idle: 0
  flyway:
    #开启
    enabled: true


mybatis-plus:
  mapper-locations: classpath:com/oddfar/campus/service/mapper/xml/*.xml
  #mybatis-plus日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# token配置
token:
  # 令牌密钥
  secret: oddfar.com
  # 令牌有效期（默认4320分钟,3天）
  expireTime: 4320

#已经弃用，在ConstantOssPropertiesUtils里
aliyun.oss.endpoint: oss-cn-beijing.aliyuncs.com
aliyun.oss.accessKeyId: XXXXXXXXXXXXXXXXXX
aliyun.oss.secret: XXXXXXXXXXXXXXXXX
aliyun.oss.bucket: campus-oddfar

#  server.tomcat.max-swallow-size = 100MB # 最重要的是这一行
