server:
  port: 9101

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus?characterEncoding=utf-8&useSSL=false
    username: campus
    password: aeDxjWpFxZKTeLhr
  redis:
    host: localhost
    port: 16379
    password: 123456
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        max-idle: 5
        min-idle: 0

swagger:
  #true开启swagger,false关闭，在Swagger2Config文件中
  show: false
